import { type Ref, watch } from 'vue'
import { buildDefaultScoringRulesFromTarget } from '@/utils/kpiScoringRulesDsl'

/**
 * Khi nhập target, tự điền thang điểm mặc định (5: >=1.2X … 1: <0.9X).
 * Chỉ ghi đè nếu ô thang điểm đang trống hoặc vẫn là bản auto lần trước.
 */
export function useAutoScoringRulesFromTarget(
  targetValue: Ref<string>,
  description: Ref<string>,
  enabled: Ref<boolean> | (() => boolean) = () => true,
) {
  let lastAutoGenerated: string | null = null

  function isEnabled(): boolean {
    return typeof enabled === 'function' ? enabled() : enabled.value
  }

  function syncFromTarget(raw: string) {
    if (!isEnabled()) return
    const n = Number.parseFloat(String(raw ?? '').trim())
    if (!Number.isFinite(n) || n <= 0) return
    const next = buildDefaultScoringRulesFromTarget(n)
    if (!next) return
    const current = description.value.trim()
    if (current && current !== lastAutoGenerated) return
    description.value = next
    lastAutoGenerated = next
  }

  watch(targetValue, (raw) => syncFromTarget(raw))

  function onScoringRulesManualInput() {
    const current = description.value.trim()
    if (current !== lastAutoGenerated) {
      lastAutoGenerated = null
    }
  }

  function resetAutoScoringRulesTracking() {
    lastAutoGenerated = null
  }

  return {
    onScoringRulesManualInput,
    resetAutoScoringRulesTracking,
    syncFromTarget,
  }
}
