import { type Ref, watch } from 'vue'

import { buildDefaultScoringRulesFromTarget } from '@/utils/kpiScoringRulesDsl'



/**

 * Khi nhập / đổi target: luôn tự sinh lại thang điểm theo target hiện tại.

 * Sửa tay thang điểm được giữ cho đến khi target đổi (lúc đó sinh lại).

 */

export function useAutoScoringRulesFromTarget(

  targetValue: Ref<string>,

  description: Ref<string>,

  enabled: Ref<boolean> | (() => boolean) = () => true,

) {

  let lastAutoGenerated: string | null = null

  /** Chặn watch target khi hydrate form từ API (tránh ghi đè thang điểm catalog). */

  let pauseAutoTargetSyncDepth = 0



  function isEnabled(): boolean {

    return typeof enabled === 'function' ? enabled() : enabled.value

  }



  /** Gọi trước khi gán target/description từ API; dispose sau khi hydrate xong. */

  function pauseAutoSyncFromTarget(): () => void {

    pauseAutoTargetSyncDepth++

    let disposed = false

    return () => {

      if (disposed) return

      disposed = true

      pauseAutoTargetSyncDepth = Math.max(0, pauseAutoTargetSyncDepth - 1)

    }

  }



  function syncFromTarget(raw: string) {

    if (pauseAutoTargetSyncDepth > 0 || !isEnabled()) return

    const n = Number.parseFloat(String(raw ?? '').trim())

    if (!Number.isFinite(n) || n <= 0) return

    const next = buildDefaultScoringRulesFromTarget(n)

    if (!next) return

    description.value = next

    lastAutoGenerated = next

  }



  watch(targetValue, (raw) => syncFromTarget(raw), { flush: 'sync' })



  function onScoringRulesManualInput(e?: Event) {

    const fromDom =

      e?.target instanceof HTMLTextAreaElement ? e.target.value : description.value

    const current = String(fromDom ?? '').trim()

    if (fromDom !== description.value) {

      description.value = fromDom

    }

    if (current !== lastAutoGenerated) {

      lastAutoGenerated = null

    }

  }



  function resetAutoScoringRulesTracking() {

    lastAutoGenerated = null

  }



  /** Sau hydrate copy/edit: baseline để so sánh; đổi target vẫn sinh lại thang điểm. */

  function markCurrentScoringRulesAsAutoBaseline() {

    const current = description.value.trim()

    lastAutoGenerated = current || null

  }



  return {

    onScoringRulesManualInput,

    resetAutoScoringRulesTracking,

    syncFromTarget,

    markCurrentScoringRulesAsAutoBaseline,

    pauseAutoSyncFromTarget,

  }

}


